/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 justin3d.glb --transform 
Files: justin3d.glb [1.7MB] > D:\WEB LATIHAN\portfolio-nextjs\public\model\justin3d-transformed.glb [195.17KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/justin3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.PaletteMaterial001} position={[-0.046, 0.766, 0.011]} rotation={[0, 0.02, 0]} />
      <group position={[-0.007, 0.768, 0.047]} rotation={[0, 0.02, 0]} scale={0.807}>
        <mesh geometry={nodes.Sphere001.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Sphere001_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.kacamta.geometry} material={materials.PaletteMaterial004} position={[-0.045, 0.77, 0.086]} rotation={[Math.PI / 2, 0, 3.121]} scale={0.037} />
      <mesh geometry={nodes.BézierCurve.geometry} material={nodes.BézierCurve.material} position={[0.132, -0.778, 0.152]} rotation={[0, 0.02, 0]} scale={0.073} />
    </group>
  )
}

useGLTF.preload('/justin3d-transformed.glb')
